import { Inter } from 'next/font/google'
import Header from '@/components/base/Header/Header';
import AboutUs from '@/components/page/Top/AboutUs';
import Contact from '@/components/page/Top/Contact';
import Member from '@/components/page/Top/Member';
import Footer from '@/components/base/Footer/Footer';
import { Flex } from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className={inter.className}>
      <Header />
      <Flex as="main" justify="center" align="center">
        <AboutUs />
      </Flex>
      <Member />
      <Member />
      <Contact/>
      <Footer />
    </div>
  )
}